# Please use Pandas dataFrame to work on the following questions
For each question, I have produced the output for you, so you know what I expect your code to generate. BE CAREFUL, once you run your code, my output will be gone.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# For this practice, please make sure that you download the "flights.csv" file to your Jupyter folder
# Read flights.csv as a dataframe called flight
flight = pd.read_csv('flights.csv')
flight

,Airport code,Country,City,Path ID,Path Order,Flow Amount (t),Latitude,Longitude
0,PRG,Czech Republic,Prague,PRG-VIE,1,NaN,50.075538,14.437800
1,VIE,Austria,Vienna,PRG-VIE,2,250.0,48.208174,16.373819
2,PRG,Czech Republic,Prague,PRG-MSQ,1,NaN,50.075538,14.437800
3,MSQ,Belarus,Minsk,PRG-MSQ,2,1200.0,53.904540,27.561524
4,PRG,Czech Republic,Prague,PRG-TMP,1,NaN,50.075538,14.437800
5,TMP,Finland,Tampere,PRG-TMP,2,800.0,61.497752,23.760954
6,PRG,Czech Republic,Prague,PRG-HAM,1,NaN,50.075538,14.437800
7,HAM,Germany,Hamburg,PRG-HAM,2,400.0,53.551085,9.993682
8,PRG,Czech Republic,Prague,PRG-ATH,1,NaN,50.075538,14.437800
9,ATH,Greece,Athens,PRG-ATH,2,150.0,37.983810,23.727539
10,PRG,Czech Republic,Prague,PRG-DUB,1,NaN,50.075538,14.437800
11,DUB,Ireland,Dublin,PRG-DUB,2,500.0,53.349805,-6.260310
12,PRG,Czech Republic,Prague,PRG-MRS,1,NaN,50.075538,14.437800
13,MRS,France,Marseille,PRG-MRS,2,800.0,43.296482,5.369780
14,PRG,Czech Republic,Prague,PRG-AMS,1,NaN,50.075538,14.437800
15,AMS,Netherlands,Amsterdam,PRG-AMS,2,50.0,52.370216,4.895168
16,PRG,Czech Republic,Prague,PRG-WAW,1,NaN,50.075538,14.437800
17,WAW,Poland,Warsaw,PRG-WAW,2,550.0,52.229676,21.012229
18,PRG,Czech Republic,Prague,PRG-LIS,1,NaN,50.075538,14.437800
19,LIS,Portugal,Lisbon,PRG-LIS,2,130.0,38.722252,-9.139337
20,PRG,Czech Republic,Prague,PRG-BEG,1,NaN,50.075538,14.437800
21,BEG,Serbia,Belgrad,PRG-BEG,2,920.0,44.786568,20.448922
22,PRG,Czech Republic,Prague,PRG-IST,1,NaN,50.075538,14.437800
23,IST,Turkey,Istanbul,PRG-IST,2,810.0,41.008238,28.978359
24,PRG,Czech Republic,Prague,PRG-DNK,1,NaN,50.075538,14.437800
25,DNK,Ukraine,Dnepropetrovsk,PRG-DNK,2,1300.0,48.464717,35.046183
26,PRG,Czech Republic,Prague,PRG-FRA,1,NaN,50.075538,14.437800
27,FRA,Germany,Frankfurt,PRG-FRA,2,1000.0,50.110922,8.682127
28,PRG,Czech Republic,Prague,PRG-SOF,1,NaN,50.075538,14.437800
29,SOF,Bulgaria,Sofia,PRG-SOF,2,380.0,42.697708,23.321868

In [3]:
# Question 1: Check the column head of the table
flight.head()

,Airport code,Country,City,Path ID,Path Order,Flow Amount (t),Latitude,Longitude
0,PRG,Czech Republic,Prague,PRG-VIE,1,NaN,50.075538,14.437800
1,VIE,Austria,Vienna,PRG-VIE,2,250.0,48.208174,16.373819
2,PRG,Czech Republic,Prague,PRG-MSQ,1,NaN,50.075538,14.437800
3,MSQ,Belarus,Minsk,PRG-MSQ,2,1200.0,53.904540,27.561524
4,PRG,Czech Republic,Prague,PRG-TMP,1,NaN,50.075538,14.437800

In [4]:
# Question 2: Find how many rows are in the table (HINT: info.)
flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airport code     30 non-null     object
 1   Country          30 non-null     object
 2   City             30 non-null     object
 3   Path ID          30 non-null     object
 4   Path Order       30 non-null     int64
 5   Flow Amount (t)  15 non-null     float64
 6   Latitude         30 non-null     float64
 7   Longitude        30 non-null     float64
dtypes: float64(3), int64(1), object(4)
memory usage: 2.0+ KB

In [5]:
# Question 3: What is the average flow amount?
# HINT: Here is one very good example of why the iloc function is useful -- the column name "Flow Amount (t)" would be
# inconvenient to type, so you might want to use the position of the column instead... If you prefer column name, that 
# is fine, too.
flight["Flow Amount (t)"].mean(axis = 0, skipna = True)

616.0

In [6]:
# Question 4: What is the highest flow amount?
flight["Flow Amount (t)"].max(axis = 0, skipna = True)

1300.0

In [ ]:
# Question 5: Which city has the flow amount of 550?
# Hint: Recall back to our discussion on the relational algebra of SELECTION and the Python bracket notation 
flight[flight["Flow Amount (t)"]==550]['City']

In [ ]:
# Now let's work with the GBI Excel sheet -- if you have done the IO lab, the file should already be in your working folder. 
# Otherwise, please go to canvas and find the file under the IO lab, download it to your working folder. Read GBI file and name it
# GBI
import numpy as np
import pandas as pd
GBI = pd.read_excel('GBI.xlsx')
GBI

In [ ]:
# Question 6: What is the average REVENUE for each Product Category? [HINT: You need to group by Product Category]
GBI.groupby('Product Category')['Revenue'].mean()

In [1]:
# Question 7: How many transations have the lowest revenue?
GBI[GBI['Revenue']==GBI['Revenue'].min()]

NameError: name 'GBI' is not defined

In [ ]:
# Question 8: What is the average revenue for each year? 
GBI.groupby('YEAR')['Revenue'].mean()

In [ ]:
# Question 9: How many unique product names are there? 
# HINT: 1. ProductDecr has all product names
# 2. unique() returns an ARRAY
# 3. numpy has a size function that returns the size of an array. Check the Web and learn how to use it

a=GBI.ProductDescr.unique()
a.size